BOWER_DIRECTORY       = 'bower_components/'
module.exports =
	BOWER_DIRECTORY       : BOWER_DIRECTORY
	BOWER_FILE            : 'bower.json'
	CHANGELOG_FILE        : 'CHANGELOG.md'
	COMPONENTS_DIRECTORY  : "#{BOWER_DIRECTORY}_/"
	DIST_DIRECTORY        : 'dist/'
	E2E_DIRECTORY         : 'e2e/'
	FONTS_DIRECTORY       : 'fonts/'
	PROTRACTOR_SCREENSHOTS: 'protractorScreenshots'
	SCRIPTS_MIN_FILE      : 'scripts.min.js'
	SCRIPTS_MIN_DIRECTORY : 'scripts/'
	SRC_DIRECTORY         : 'src/'
	STATS_DIRECTORY       : 'stats/stats/'
	STATS_DIST_DIRECTORY  : 'stats/'
	STYLES_MIN_DIRECTORY  : 'styles/'
	STYLES_MIN_FILE       : 'styles.min.css'
	TEMP_DIRECTORY        : '.temp/'
	TEST_RESULTS_DIRECTORY: 'testResults'
	VENDOR_DIRECTORY      : 'vendor/'
